### ISSUE TITLE
Remove Non-DotFiles

### ISSUE THREAD

**Issue by j-crowe** [jaredallard/dotfiles#1]
There are several files that don't have a single dot in the filename. Plz remove them.

**Comment by j-crowe** [comment]
bump

**Comment by j-crowe** [comment]
bump

**Comment by j-crowe** [comment]
blormp

**Comment by j-crowe** [comment]
Gormp

**Comment by jaredallard** [comment]
Wow, this is a serious matter.... totally didn't notice this. Sorry to let you all down

**Comment by j-crowe** [comment]
@jaredallard flormp
